---
- name: Deploy game.py
  hosts: 127.0.0.1
#   become: yes
  
  vars:
    working_directory: ../app

  tasks:
    - name: Install python3
      yum: name=python3 state=latest
      
    - name: Install pip3
      yum: name=python3-pip state=present 
    
    - name: Install packages
      pip:
        name:
          - numpy
          - tkinter 
          - random

    - name: Make code executable 
      ansible.builtin.shell:
        cmd: chmod ugo +rwx game.py
        chdir: "{{ working_directory }}"

    - name: Run code
      ansible.builtin.shell:
        cmd: python3 game.py
        chdir: "{{ working_directory }}"

...
